import "~/styles/globals.css";
import { ThemeProvider } from "~/components/theme-provider";
import NavMenu from "~/components/NavMenu";
import { ModeToggle } from "~/components/DarkMode-Toggle";

import { GeistSans } from "geist/font/sans";

export const metadata = {
  title: "Oscar Gamez - Portfolio",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={`${GeistSans.variable}`}>
      <body>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <div className="mx-5 my-5 flex flex-row justify-between gap-2">
            <NavMenu />
            <ModeToggle />
          </div>
          <div className="container">{children}</div>
        </ThemeProvider>
      </body>
    </html>
  );
}
